### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by kyeshmz** [bareblackfoot/lddp-tf-faster-rcnn#1]
Hi, thank you for the awsome work!
Just wondering how one would go about training their own model for their dataset.
I was curious about this as it does not eliminate small objects for small object detection.

I notice in the readme that I could use this on my own images using the pretrained models and weights, but how would I make my own model if say the dataset does not contain any of the names on coco or voc?

**Comment by bareblackfoot** [comment]
You can train the network with your own dataset by adding dataset file in "./lib/dataset/yourdataset.py" and add the path and name of the dataset in  "./lib/dataset/factory.py" :)
